version: 2
jobs:
  build:
    filters:
      branches:
        only:
          - master
          - develp
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
